//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MemoEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Change Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string btn_change_folder {
            get {
                return ResourceManager.GetString("btn_change_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string btn_delete {
            get {
                return ResourceManager.GetString("btn_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string btn_new {
            get {
                return ResourceManager.GetString("btn_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string btn_new_folder {
            get {
                return ResourceManager.GetString("btn_new_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string btn_save {
            get {
                return ResourceManager.GetString("btn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Current Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string command_addtime {
            get {
                return ResourceManager.GetString("command_addtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string command_copy {
            get {
                return ResourceManager.GetString("command_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string command_cut {
            get {
                return ResourceManager.GetString("command_cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string command_delete {
            get {
                return ResourceManager.GetString("command_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string command_find {
            get {
                return ResourceManager.GetString("command_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find Next과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string command_find_next {
            get {
                return ResourceManager.GetString("command_find_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Goto과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string command_goto {
            get {
                return ResourceManager.GetString("command_goto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string command_new {
            get {
                return ResourceManager.GetString("command_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string command_paste {
            get {
                return ResourceManager.GetString("command_paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string command_rename {
            get {
                return ResourceManager.GetString("command_rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string command_replace {
            get {
                return ResourceManager.GetString("command_replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string command_save {
            get {
                return ResourceManager.GetString("command_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string command_selectall {
            get {
                return ResourceManager.GetString("command_selectall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string findwin_cancel {
            get {
                return ResourceManager.GetString("findwin_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot find 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string findwin_cannot_find_message {
            get {
                return ResourceManager.GetString("findwin_cannot_find_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Direction과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string findwin_direction {
            get {
                return ResourceManager.GetString("findwin_direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Down과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string findwin_direction_down {
            get {
                return ResourceManager.GetString("findwin_direction_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Up과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string findwin_direction_up {
            get {
                return ResourceManager.GetString("findwin_direction_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string findwin_find {
            get {
                return ResourceManager.GetString("findwin_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text to find과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string findwin_find_content {
            get {
                return ResourceManager.GetString("findwin_find_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string findwin_replace {
            get {
                return ResourceManager.GetString("findwin_replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text to replace과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string findwin_replace_content {
            get {
                return ResourceManager.GetString("findwin_replace_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find/Replace과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string findwin_title {
            get {
                return ResourceManager.GetString("findwin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string memo_filename_prefix {
            get {
                return ResourceManager.GetString("memo_filename_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New Folder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string memo_foldername_prefix {
            get {
                return ResourceManager.GetString("memo_foldername_prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change Font과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string menu_change_font {
            get {
                return ResourceManager.GetString("menu_change_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string menu_edit {
            get {
                return ResourceManager.GetString("menu_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string menu_exit {
            get {
                return ResourceManager.GetString("menu_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string menu_file {
            get {
                return ResourceManager.GetString("menu_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string menu_help {
            get {
                return ResourceManager.GetString("menu_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string menu_info {
            get {
                return ResourceManager.GetString("menu_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string menu_new {
            get {
                return ResourceManager.GetString("menu_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string menu_save {
            get {
                return ResourceManager.GetString("menu_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top Most과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string menu_topmost {
            get {
                return ResourceManager.GetString("menu_topmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string menu_view {
            get {
                return ResourceManager.GetString("menu_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Want to delete?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string msg_delete {
            get {
                return ResourceManager.GetString("msg_delete", resourceCulture);
            }
        }
    }
}
