//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smith.WPF.HtmlEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiText() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Smith.WPF.HtmlEditor.Resources.UiText", typeof(UiText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Bottom과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Align_Bottom {
            get {
                return ResourceManager.GetString("Align_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Align_Center {
            get {
                return ResourceManager.GetString("Align_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Align_Default {
            get {
                return ResourceManager.GetString("Align_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Align_Left {
            get {
                return ResourceManager.GetString("Align_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Align_Right {
            get {
                return ResourceManager.GetString("Align_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Align_Top {
            get {
                return ResourceManager.GetString("Align_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bold과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Bold {
            get {
                return ResourceManager.GetString("Button_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Browse과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Browse {
            get {
                return ResourceManager.GetString("Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bulleted List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_BulletedList {
            get {
                return ResourceManager.GetString("Button_BulletedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear Style과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_ClearStyle {
            get {
                return ResourceManager.GetString("Button_ClearStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code Mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_CodeMode {
            get {
                return ResourceManager.GetString("Button_CodeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_FontColor {
            get {
                return ResourceManager.GetString("Button_FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Indent과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Indent {
            get {
                return ResourceManager.GetString("Button_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert Hyperlink과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_InsertHyperlink {
            get {
                return ResourceManager.GetString("Button_InsertHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert Image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_InsertImage {
            get {
                return ResourceManager.GetString("Button_InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert Table과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_InsertTable {
            get {
                return ResourceManager.GetString("Button_InsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Italic과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Italic {
            get {
                return ResourceManager.GetString("Button_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Justify Center과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_JustifyCenter {
            get {
                return ResourceManager.GetString("Button_JustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Justify Full과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_JustifyFull {
            get {
                return ResourceManager.GetString("Button_JustifyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Justify Left과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_JustifyLeft {
            get {
                return ResourceManager.GetString("Button_JustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Justify Right과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_JustifyRight {
            get {
                return ResourceManager.GetString("Button_JustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_LineColor {
            get {
                return ResourceManager.GetString("Button_LineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Numbered List과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_NumberedList {
            get {
                return ResourceManager.GetString("Button_NumberedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Outdent과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Outdent {
            get {
                return ResourceManager.GetString("Button_Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subscript과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Subscript {
            get {
                return ResourceManager.GetString("Button_Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Superscript과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Superscript {
            get {
                return ResourceManager.GetString("Button_Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Underline과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_Underline {
            get {
                return ResourceManager.GetString("Button_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom In과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_ZoomIn {
            get {
                return ResourceManager.GetString("Button_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zoom Out과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_ZoomOut {
            get {
                return ResourceManager.GetString("Button_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Cmd_Copy {
            get {
                return ResourceManager.GetString("Cmd_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cut과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Cmd_Cut {
            get {
                return ResourceManager.GetString("Cmd_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Cmd_Delete {
            get {
                return ResourceManager.GetString("Cmd_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paste과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Cmd_Paste {
            get {
                return ResourceManager.GetString("Cmd_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Cmd_Redo {
            get {
                return ResourceManager.GetString("Cmd_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Cmd_SelectAll {
            get {
                return ResourceManager.GetString("Cmd_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Cmd_Undo {
            get {
                return ResourceManager.GetString("Cmd_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Header_Default {
            get {
                return ResourceManager.GetString("Header_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First Column과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Header_FirstColumn {
            get {
                return ResourceManager.GetString("Header_FirstColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First Row과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Header_FirstRow {
            get {
                return ResourceManager.GetString("Header_FirstRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First Row And Column과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Header_FirstRowAndColumn {
            get {
                return ResourceManager.GetString("Header_FirstRowAndColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alt Text과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_AltText {
            get {
                return ResourceManager.GetString("Label_AltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Border과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Border {
            get {
                return ResourceManager.GetString("Label_Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Columns과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ColCount {
            get {
                return ResourceManager.GetString("Label_ColCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   H Space과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_HSpace {
            get {
                return ResourceManager.GetString("Label_HSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alignment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ImgAlignment {
            get {
                return ResourceManager.GetString("Label_ImgAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ImgHeight {
            get {
                return ResourceManager.GetString("Label_ImgHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ImgTitle {
            get {
                return ResourceManager.GetString("Label_ImgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ImgWidth {
            get {
                return ResourceManager.GetString("Label_ImgWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Link to과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Link {
            get {
                return ResourceManager.GetString("Label_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Preview과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_NoPreview {
            get {
                return ResourceManager.GetString("Label_NoPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Padding과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Padding {
            get {
                return ResourceManager.GetString("Label_Padding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rows과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_RowCount {
            get {
                return ResourceManager.GetString("Label_RowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Spacing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Spacing {
            get {
                return ResourceManager.GetString("Label_Spacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alignment과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TableAlignment {
            get {
                return ResourceManager.GetString("Label_TableAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Border과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TableBorder {
            get {
                return ResourceManager.GetString("Label_TableBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Header과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TableHeader {
            get {
                return ResourceManager.GetString("Label_TableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TableHeight {
            get {
                return ResourceManager.GetString("Label_TableHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TableTitle {
            get {
                return ResourceManager.GetString("Label_TableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TableWidth {
            get {
                return ResourceManager.GetString("Label_TableWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_Text {
            get {
                return ResourceManager.GetString("Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_URL {
            get {
                return ResourceManager.GetString("Label_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   V Space과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_VSpace {
            get {
                return ResourceManager.GetString("Label_VSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert Hyperlink과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WinTitle_InsertHyperlink {
            get {
                return ResourceManager.GetString("WinTitle_InsertHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert Image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WinTitle_InsertImage {
            get {
                return ResourceManager.GetString("WinTitle_InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert Table과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WinTitle_InsertTable {
            get {
                return ResourceManager.GetString("WinTitle_InsertTable", resourceCulture);
            }
        }
    }
}
